### ISSUE TITLE
实战获取当前时间插件示例，使用Azure的gpt-4o模型，Azure接口报异常。

### ISSUE THREAD

**Issue by feynmanloo** [AIDotNet/Thor#15]
实战获取当前时间插件示例，使用Azure的gpt-4o模型，Azure接口报异常：
Headers:
x-ms-region: REDACTED
apim-request-id: REDACTED
x-ratelimit-remaining-requests: REDACTED
x-ms-rai-invoked: REDACTED
x-envoy-upstream-service-time: REDACTED
X-Request-ID: REDACTED
ms-azureml-model-error-reason: REDACTED
ms-azureml-model-error-statuscode: REDACTED
ms-azureml-model-time: REDACTED
x-ms-client-request-id: 6b1121d6-d6a8-4662-a481-a43cf6522d31
Strict-Transport-Security: REDACTED
azureml-model-session: REDACTED
X-Content-Type-Options: REDACTED
x-ratelimit-remaining-tokens: REDACTED
Date: Thu, 13 Jun 2024 08:20:41 GMT
Content-Length: 269
Content-Type: application/json

Azure.RequestFailedException: Invalid schema for function 'TimeInformationPlugin-GetCurrentUtcTime': None is not of type 'object', 'boolean'.
Status: 400 (model_error)
ErrorCode: invalid_function_parameters

Content:
{
  "error": {
    "message": "Invalid schema for function 'TimeInformationPlugin-GetCurrentUtcTime': None is not of type 'object', 'boolean'.",
    "type": "invalid_request_error",
    "param": "functions[0].parameters",
    "code": "invalid_function_parameters"
  }
}

备注：使用openai官方提供的gpt-4o是没问题的。跳过代理，直接使用Azure的渠道，也是没问题的。

**Comment by feynmanloo** [comment]
@239573049  大佬，这个有解吗？

**Comment by 239573049** [comment]
目前已知Azure扩展的版本过低导致bug

**Comment by 239573049** [comment]
对于azure我们使用HttpClient直接请求不在依赖Azure openAI  SDK
